name: Check
on:
  push:
permissions:
  contents: read
jobs:
  go-checks:
    name: Go lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.18.4'  # allow higher patchlevels

      - name: golangci-lint
        id: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3
          only-new-issues: true
        continue-on-error: true

      - name: go test
        run: go test -v ./...

      - name: Fail on skipped errors
        if: steps.lint.outcome != 'success'
        run: echo "Linting errors" && exit 1

